package com.manacommunity.api.model;

public enum PostType {
    GENERAL,
    CLASSIFIED,
    POLL,
    LOST_FOUND,
    ANNOUNCEMENT,
    QUESTION,
    SUGGESTION,
    APPRECIATION,
    COMPLAINT,
    ARTICLE,
    EVENT,
    JOB,
    MARKETPLACE,
    HEALTHCARE,
    SPORTS,
    FOOD,
    VENDOR_PROMOTION,
    PROPERTY,
    EMERGENCY,
    ACHIEVEMENT,
    BIRTHDAY,
    COMMUNITY_NEWS,
    MAINTENANCE,
    COMMITTEE_NOTICE,
    MEETING
}
